In [1]:
import numpy as np

## 训练二元分类器

In [2]:
data_path = './mnist_data/mnist.npz'
f = np.load(data_path)
X_train, y_train = f['x_train'], f['y_train']
X_test, y_test = f['x_test'], f['y_test']

### 数字 5 检测器

In [8]:
y_train_5 = (y_train == 5)
y_test_5 = (y_test == 5)

In [28]:
X_train = X_train.reshape((60000, 784))
X_test = X_test.reshape((10000, 784))

In [29]:
from sklearn.linear_model import SGDClassifier

sgd_clf = SGDClassifier(random_state=42)
sgd_clf.fit(X_train, y_train_5)

SGDClassifier(random_state=42)

In [30]:
some_digit = X_train[0]

sgd_clf.predict([some_digit])

array([ True])

In [31]:
y_train[0]

5

数字 5 检测器验证正确！

## 性能测量

### 使用交叉验证测量准确率

In [32]:
from sklearn.model_selection import cross_val_score

cross_val_score(sgd_clf, X_train, y_train, cv=3, scoring="accuracy")

array([0.909  , 0.90235, 0.9164 ])

我们使用 DummyClassifier 来看看不是5的分类情况

In [33]:
from sklearn.dummy import DummyClassifier

dummy_clf = DummyClassifier()
dummy_clf.fit(X_train, y_train_5)
any(dummy_clf.predict(X_train))

False

In [34]:
cross_val_score(dummy_clf, X_train, y_train_5, cv=3, scoring="accuracy")

array([0.90965, 0.90965, 0.90965])

由此可见，不能只看准确率

### 混淆矩阵

In [35]:
from sklearn.model_selection import cross_val_predict

y_train_pred = cross_val_predict(sgd_clf, X_train, y_train_5, cv=3)

In [36]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_train_5, y_train_pred)
cm

array([[53822,   757],
       [  867,  4554]])

In [38]:
y_train_prefect_predictions = y_train_5
confusion_matrix(y_train_5, y_train_prefect_predictions)

array([[54579,     0],
       [    0,  5421]])